server:
  port: 8082

hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城购物车"
    package: com.hmall.cart.controller
feign:
  okhttp:
    enabled: true # 开启OKHttp功能

spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.163.129:8090  # Sentinel控制台地址
      http-method-specify: true # 是否将HTTP请求的Method作为资源路由的标识符
